eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
     registerWithEureka: false

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
      metrics:
        rollingStats:
          timeInMilliseconds: 120000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 10000

feign:
  hystrix:
    enabled: true

events-service:
  ribbon:
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 2

users-service:
  ribbon:
    MaxAutoRetriesNextServer: 2

notes-service:
  ribbon:
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 2

logging.level:
  kpi.ipt.organizer.frontend.client: DEBUG
