eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
     registerWithEureka: false

events-service:
  ribbon:
    MaxAutoRetriesNextServer: 2

users-service:
  ribbon:
    MaxAutoRetriesNextServer: 2

notes-service:
  ribbon:
    MaxAutoRetriesNextServer: 2

logging.level:
  kpi.ipt.organizer.frontend.client: DEBUG
