spring:
  data:
    mongodb:
      database: notes_db
      #uri: mongodb://127.0.0.1:27101,127.0.0.1:27102/?replicaSet=notesRs
      uri: mongodb://127.0.0.1:27111

logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG