spring:
  data:
    mongodb:
      database: notes_db
      uri: mongodb://127.0.0.1:27111

management:
  health:
    sensitive: false
  security:
    enabled: false

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
