spring:
  datasource:
    password: users_password
    username: users_admin
    url: jdbc:postgresql://localhost:5432/users_db
  jpa:
    show-sql: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging.level.org.springframework.orm.jpa.JpaTransactionManager: DEBUG
