spring:
  datasource:
    password: users_password
    username: users_admin
    url: jdbc:postgresql://localhost:5432/users_db
  jpa:
    show-sql: true

management:
  health:
    sensitive: false
  security:
    enabled: false

# to disable reporting DOWN to Eureka when RabbitMQ is inaccessible
management.health.defaults.enabled: false

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging.level.org.springframework.orm.jpa.JpaTransactionManager: DEBUG
